kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webfile
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi


---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: website
          mountPath: /var/www/html
  volumes:
    - name: website
      persistentVolumeClaim:
        claimName: webfile